/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as GenerateImport } from './routes/generate'
import { Route as IndexImport } from './routes/index'
import { Route as YamlConfigIdImport } from './routes/yaml.$configId'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const GenerateRoute = GenerateImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const YamlConfigIdRoute = YamlConfigIdImport.update({
  id: '/yaml/$configId',
  path: '/yaml/$configId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/yaml/$configId': {
      id: '/yaml/$configId'
      path: '/yaml/$configId'
      fullPath: '/yaml/$configId'
      preLoaderRoute: typeof YamlConfigIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/upload': typeof UploadRoute
  '/yaml/$configId': typeof YamlConfigIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/upload': typeof UploadRoute
  '/yaml/$configId': typeof YamlConfigIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/upload': typeof UploadRoute
  '/yaml/$configId': typeof YamlConfigIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate' | '/upload' | '/yaml/$configId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate' | '/upload' | '/yaml/$configId'
  id: '__root__' | '/' | '/generate' | '/upload' | '/yaml/$configId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateRoute: typeof GenerateRoute
  UploadRoute: typeof UploadRoute
  YamlConfigIdRoute: typeof YamlConfigIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateRoute: GenerateRoute,
  UploadRoute: UploadRoute,
  YamlConfigIdRoute: YamlConfigIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/generate",
        "/upload",
        "/yaml/$configId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/generate": {
      "filePath": "generate.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/yaml/$configId": {
      "filePath": "yaml.$configId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
